{% set name = "gitignore-parser" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gitignore_parser-{{ version }}.tar.gz
  sha256: d0150d81889251d00cde6cf38931ab5613ca1109f5b3905a232c8458ff0d6991

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gitignore_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mherrmann/gitignore_parser
  summary: A spec-compliant gitignore parser for Python 3.5+
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
