{% set name = "gitignore-parser" %}
{% set version = "0.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gitignore_parser-{{ version }}.tar.gz
  sha256: fa10fde48b44888eeefac096f53bcdad9b87a4ffd7db788558dbdf71ff3bc9db

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - gitignore_parser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mherrmann/gitignore_parser
  summary: A spec-compliant gitignore parser for Python 3.5+
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
