{% set name = "gitignore-parser" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gitignore_parser-{{ version }}.tar.gz
  sha256: ad22d69baafc9eaeff4a3a7c87da089aa416df50c72c3bc14a7aa0a1a9bc6472

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gitignore_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mherrmann/gitignore_parser
  summary: A spec-compliant gitignore parser for Python 3.5+
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
